### ISSUE TITLE
Поворот изображения

### ISSUE THREAD

**Issue by PavelG94** [plzombie/Image_processing#1]
Алгоритм поворота рабочий (проверял в Qt), синтаксических ошибок нет. Но попытки протестировать функцию в текущем проекте оказались неудачными, причину найти не могу. Ткни, пожалуйста, туда, где нужно что - либо поправить.

**Comment by plzombie** [comment]
Там куча мелких ошибок. Пофиксил. Проверить можно, меняя угол, возвращаемый функцией viewerOCRGetAngle()
