### ISSUE TITLE
Распределение оставшихся подзадач к первому модулю

### ISSUE THREAD

**Issue by PavelG94** [plzombie/Image_processing#3]
Вопрос такой: как распределим оставшиеся подзадачи выравнивания и сегментации изображения.

**Comment by plzombie** [comment]
Выравнивание изображения состоит из двух подзадач:

- нахождение угла, на который надо повернуть изображение (задача Павла Орехова).
- поворот изображения на угол (твоя задача; уже выполнена).

Весь код, который соединяет подзадачи, уже давно написан (смотри функцию viewerOCR()), так что выранивание уже распределили.
Для сегментации нужен алгоритм нахождения линий, который мы сейчас разбираем на парах. Без него я не знаю как распределять задачи (делать кому-то одному весь процесс нахождения символов - слишком сложно).
Если хочешь, можешь пока взять функцию viewerOCRCropImage, там кода буквально на 10 строк, только пока нечем её тестировать.
